### ISSUE TITLE
Unable to update settings due to missing import

### ISSUE THREAD

**Issue by guitarmanvt** [soltra-adapters/adapter-snort#3]
Steps to reproduce:
1. Navigate to Adapters > Snort Rules from STIX
2. Click **Settings**
3. Enter a new value in the **Snort Rules Filename Prefix** field.
4. Click **Update Settings**

Expected behavior: Return to first page.

Actual behavior: Error message, _"The administrators have been notified of this issue
An error occurred"_

Crashlog entry:

```
App: /adapter/snort_adapter/settings/
Message: global name 'HttpResponseRedirect' is not defined
Traceback (most recent call last):
  File "/usr/share/edge/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/edge/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/lib/edge/python/adapters/snort_adapter/views.py", line 107, in settings
    return process_settings(request)
  File "/usr/share/edge/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/lib/edge/python/adapters/snort_adapter/views.py", line 41, in process_settings
    return HttpResponseRedirect(reverse('snort_process'))
NameError: global name 'HttpResponseRedirect' is not defined
```

**Comment by guitarmanvt** [comment]
Tested with Edge 2.9-rc2(a)

**Comment by guitarmanvt** [comment]
Fixed in https://github.com/soltra-adapters/adapter-snort/commit/670ea4d9edecd00e746cf213cd8edd453fc0b6f0
